spring:
  application:
    name: space-cats-market

application:
  payment-service:
    base-path: http://localhost:8089
    payments: ${application.payment-service.base-path}/payment-service/v1/payments
